# Generated by Django 4.2.2 on 2023-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Description',
            field=models.CharField(max_length=300),
        ),
    ]
